version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    container_name: catalog.api      
    depends_on:
      - catalogdb
    ports:
      - "8000:80"
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    container_name: basket.api      
    depends_on:
      - basketdb
    ports:
      - "8001:80"
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

