version: '3.4'

services:
  catalogdb:
    image: mongo
    
  basketdb:
    image: redis:alpine

  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest

  discountdb:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4  

  portainer:
    image: portainer/portainer-ce

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    container_name: catalog.api      
    depends_on:
      - catalogdb
    ports:
      - "8000:80"
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    container_name: basket.api      
    depends_on:
      - basketdb
    ports:
      - "8001:80"
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

volumes:
  mongo_data:
  postgres_data:
  pgadmin_data:
  portainer_data: