version: '3.4'

services:
  catalogdb:
    image: mongo

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://localhost:27017"
    ports:
      - "8000:80"

volumes:
  mongo_data: